### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/COLLAB-MOVIES#1]
IT IS TIME:

- [x] Say Hello and a background summary
- [x] State personal goals with this project
- [ ] Also intro the project idea

**Comment by Medic1111** [comment]
- Intro Complete
- Personal Goals Medic: Agile/Scrum, Git workflow
- Personal Goals Denis: API server/third-party
- Intro to Project Idea: Movies Application
