### ISSUE TITLE
Wireframe and Flow

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/COLLAB-MOVIES#11]
In order to accomplish this Epic, we must:

- [x] Determine number of screens we will have
- [x] Determine the actions of each screen
- [x] Create a low fidelity wireframe
- [x] Determine the navigation process between screens forward
- [x] Determine the navigation process between screens backwards

**Comment by Medic1111** [comment]
1 - HOME: SINGLE PAGE: 3 sections
 2- AUTH: PAGE
 3- SEARCH: PAGE

BASED ON SCREENS:

### HOME
- NAV: LOGO, HOME, LINK, SERIES, MOVIES, SEARCH, HAMBURGER MENU
- API serving series vs movies
- HERO WITH A FEATURED RANDOM MOVIE
- LISTS: SPLIT GENRE, SUGGESTIONS
- FOOTER (LARGER): CONTACT US

### SEARCH
- NAV 
- FORM (extra feature: filter)
- DISPLAY TITLES (GRID) EMPTY INITIALLY

### Hamburger menu: 
not logged in: display none
logged: CRUD 

### AUTH
- AUTH components (LOGIN)-> (REGISTER)
- Possibly modal

##### NOT LOGIN IN USER

- We can see the entire content
- Nav: Login/sign up, hamburger menu 
- Click on a movie: Suggest Register
- Not Logged in user can access second 

##### LOGGED IN

- HOME: SEES ENTIRE PAGE
- Specific search: search
- add/move personal lists

**Comment by DenisKantic** [comment]
I think we can close this, because many things has changed from original first plan and 90% and I think more from this is done currently.
