### ISSUE TITLE
Expectation

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/COLLAB-MOVIES#2]
TEAM AND PROJECT

- [x] Discuss team expectation
- [x] Address commitment hours
- [x] Address Sprint meetings structure
- [x] Resolving conflicts

**Comment by Medic1111** [comment]
Denis:
- Support
- Quality

Gabbies:
- Communication

TEAM:
- Partnership
- Drop Ego

Availability:
- Denis: Flexible 2hrs/day
- Medic: Friday, sat, sunday

(at least 2 hrs: meeting)

Sprint: weekly

Resolving conflicts: 
- Conflict meeting
- Rock paper scissors
