### ISSUE TITLE
Project- Prep

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/COLLAB-MOVIES#3]
1. Deciding on tech stack

- [x] Server
- [x] Client
- [x] DB
- [x] Deployment
- [ ] Third Party API
- [x] Testing
- [x] Coding standards
- [x] GH workflow
- [x] Branches
- [x] Individual responsibilities
- [x] Access, (dotenv)

2. Features

- [x] Discuss all wanted features
- [x] Separate the MVP
- [x] Turn each MVP Feature into Epic with subtasks
- [x] Prioritize Epics
- [x] Prioritize subtasks
- [ ] Stipulate Deadline for MVP
- [x] Define success
- [x] Low-fidelity wireframe tool
- [ ] Sketch low-fide 

3. Values

- [x] Name the app
- [ ] Vision statement
- [x] Create Repo
- [x] Initiate readme

**Comment by Medic1111** [comment]
# NUMBER ONE

1. Node, Express
3. React (CRA)
4. MongoDB(mongoose)
5. Heroku/ netlify(dev)
6. API: TBD
7. Jest, Supertest, Postman
8. CSS
9. GH Workflow: Main -> Dev -> Local working branches
10. Merged Work
11. ThirdPartyApi key = "brand new api key", MongoDB Atlas Collab# NUMBER TWO:

- Filter by: Genre of movie, Published year
- Authentication: MVP -> Login/ Registration, integration with DB, Tokens/cookie/session, Encryption (priority:2)
- Search by title: MVP -> Get api key for team-> Form -> Fetch from third party API- Set state list (priority:3)
- Lists: MVP -> Client side -> Integration with DB -> CRUD  (priority:2)

# SUCCESS: 

Dennis: Client side working well, Implement own ideas, functionality, clean.
Medic: Quality functionality, Bug free, Good UX

# SKETCH lATER

# NUMBER3

- Movieland
- 

# LOW-FID
- Photoshop
